[package]
name = "ast_interpreter"
version = "0.1.0"
authors = ["mtXTJocj <mtXTJocj@yahoo.co.jp>"]
edition = "2018"

[dependencies]
lexical_analyzer = {path="../lexical_analyzer"}
syntax_analyzer = {path="../syntax_analyzer"}
